"""Change category icon field to Text for SVG support

Revision ID: 284f94abb6bc
Revises: 65465371c36e
Create Date: 2025-11-16 22:00:07.513570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '284f94abb6bc'
down_revision = '65465371c36e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.alter_column('icon',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.alter_column('icon',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)

    # ### end Alembic commands ###
