"""Remove ticket_id column and change date to Date type

Revision ID: 46e5bc1dffe8
Revises: 69ec18dd0f20
Create Date: 2025-11-16 16:27:25.383087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46e5bc1dffe8'
down_revision = '69ec18dd0f20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Date(),
               existing_nullable=False,
               postgresql_using="TO_DATE(date, 'DD Mon YYYY')")
        batch_op.drop_index(batch_op.f('ix_notes_ticket_id'))
        batch_op.drop_column('ticket_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ticket_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.create_index(batch_op.f('ix_notes_ticket_id'), ['ticket_id'], unique=False)
        batch_op.alter_column('date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###
